version: 0.2

phases:
  install:
    commands:
      - echo current node version `node --version`
      - echo Installing system packages...
      - echo Installing global dependencies...
      - npm install -g yarn
      - yarn global add lerna
  pre_build:
    commands:
      - echo Bootstrap source code...
      - yarn
      - lerna bootstrap
  build:
    commands:
      - echo Build started on `date`
      - node ./packages/ex-lerna-core/index.js
  post_build:
    commands:
      - echo Build completed on `date`
      - ./scripts/release.sh
